- name: download myprofiler
  get_url:
    url: https://github.com/KLab/myprofiler/releases/download/0.2/myprofiler.linux_amd64.tar.gz
    checksum: sha1:b3eddc558a2ec5da4721edbb2c9a360f1d05b124
    dest: /tmp/myprofiler.tar.gz

- name: install myprofiler
  unarchive:
    remote_src: yes
    src: /tmp/myprofiler.tar.gz
    dest: /usr/local/bin

- name: put command
  template:
    src: 99-isucon-myprofiler.sh
    dest: /etc/profile.d/99-isucon-myprofiler.sh
